# Generated by Django 4.1.3 on 2023-01-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='None')),
                ('mobile', models.BigIntegerField(default=0)),
                ('occupation', models.TextField(default='None')),
                ('income', models.IntegerField(default=0)),
            ],
        ),
    ]
