# Generated by Django 4.1.3 on 2023-01-21 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familymembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('expense', models.FloatField(max_length=100000000000000000)),
                ('date', models.DateField(blank=True, null=True)),
                ('membername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familymembers.familymembers')),
            ],
        ),
    ]
